src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('students/', include("student.urls")),

    path('teacher/', include("teacher.urls")),

    path('group/', include("group.urls")),

    path('account/', include("user_account.urls")),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/teacher/urls.py
from django.urls import path

from teacher.views import TeacherCreateViews, TeacherListView, \
    TeacherUpdateViews, TeacherDeleteViews

app_name = 'teacher'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('edit/<int:pk>', TeacherUpdateViews.as_view(), name='edit'),
    path('del/<int:pk>', TeacherDeleteViews.as_view(), name='del'),
    path('add', TeacherCreateViews.as_view(), name='add'),
]

src/group/models.py
from django.db import models

# Create your models here.
from faker import Faker

from teacher.models import Teacher


class Group(models.Model):
    group_num = models.IntegerField(null=False, default=0)
    teachers = models.ForeignKey(to=Teacher, null=True, on_delete=models.SET_NULL, related_name='group')

    def __str__(self):
        return f'Group - {self.group_num}'

src/teacher/models.py
from django.db import models

# Create your models here.


class Teacher(models.Model):
    first_name = models.CharField(max_length=40, null=False)
    last_name = models.CharField(max_length=25, null=False)
    email = models.EmailField(max_length=40, null=True)
    phone_number = models.CharField(max_length=14, null=False)
    gender = models.CharField(max_length=10, default='male', null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email} {self.phone_number}"

src/teacher/forms.py
from django.forms import ModelForm

from teacher.models import Teacher


class TeacherAddForm(ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"


class TeacherEditForm(ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"

src/teacher/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, CreateView, DeleteView, ListView

from teacher.forms import TeacherAddForm, TeacherEditForm
from teacher.models import Teacher


class TeacherListView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = 'teacher_list.html'
    context_object_name = 'teacher_list'
    login_url = reverse_lazy('login')

    def get_queryset(self):
        request = self.request
        qs = super().get_queryset()
        qs = qs.order_by('-id')

        if request.GET.get('fname'):
            qs = qs.filter(first_name=request.GET.get('fname'))

        if request.GET.get('lname'):
            qs = qs.filter(last_name=request.GET.get('lname'))

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = "Teacher list"
        return context


class TeacherUpdateViews(LoginRequiredMixin, UpdateView):
    model = Teacher
    template_name = 'teacher_edit.html'
    form_class = TeacherEditForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('teacher:list')


class TeacherCreateViews(LoginRequiredMixin, CreateView):
    model = Teacher
    template_name = 'teacher_add.html'
    form_class = TeacherAddForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('teacher:list')


class TeacherDeleteViews(LoginRequiredMixin, DeleteView):
    model = Teacher
    template_name = 'teacher_del.html'
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse('teacher:list')

src/teacher/templates/teacher_add.html
{% extends 'base.html' %}

{%block content%}
    <form method="post">
     {%csrf_token%}
     {{ form.as_p }}
    <input type="submit" value="Create"><br>
    </form>
{%endblock%}

src/teacher/templates/teacher_del.html
{% extends 'base.html' %}

{%block content%}
    <form method="post">
     {%csrf_token%}
     <h1>Вы уверены?</h1>
    <button type="submit" class="btn btn-danger">DEL</button>
        <a href="{% url 'teacher:list' %}" class="btn btn-success">Cancel</a>
    </form>
{%endblock%}

src/teacher/templates/teacher_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block content%}
    <form method="post">
     {%csrf_token%}
     {{ form|crispy }}

    <input type="submit" value="Save"><br>
    </form>
{% with group_list=teacher.group.all %}
    {% include 'includes/group_table.html' %}
{% endwith %}
{%endblock%}

src/teacher/templates/teacher_list.html
{% extends 'base.html' %}

{%block content%}
<form>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">First name</span>
          </div>
          <input  name="fname" type="text" class="form-control" placeholder="First name" aria-label="firstname" aria-describedby="basic-addon1">

          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Last name</span>
          </div>
          <input  name="lname" type="text" class="form-control" placeholder="Last name" aria-label="lastname" aria-describedby="basic-addon1">

          <button type="submit" class="btn btn-info">Search</button>
        </div>
    </form>

{% for teacher in teacher_list %}
    {{teacher.id}}
    <a href = "{% url 'teacher:edit' teacher.id %}">{{teacher.first_name}} {{teacher.last_name}}</a>
    {{teacher.email}}
    <a href = "{% url 'teacher:del' teacher.id %}" class="btn btn-danger">DEL</a>
    <br>
    {%empty%}
    <p>Sorry,list is empty</p>
{% endfor %}

{% include 'includes/pagination.html' %}

{%endblock%}

src/teacher/templates/teachers_add.html
{% extends 'base.html' %}

{%block content%}
    <form method="post">
     {%csrf_token%}
     {{ form.as_p }}
    <input type="submit" value="Create"><br>
    </form>
{%endblock%}