src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('students/', include("student.urls")),

    path('teacher/', include("teacher.urls")),

    path('group/', include("group.urls")),

    path('account/', include("user_account.urls")),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/group/urls.py
from django.urls import path

from group.views import GroupListView, GroupUpdateViews, GroupCreateViews

app_name = 'group'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('add', GroupCreateViews.as_view(), name='add'),
    path('edit/<int:pk>', GroupUpdateViews.as_view(), name='edit'),
]

src/student/urls.py
from django.urls import path

from student.views import StudentsListView, \
    StudentsUpdateViews, StudentsCreateViews, StudentsDeleteView

app_name = 'students'

urlpatterns = [
    path('', StudentsListView.as_view(), name='list'),
    path('add/', StudentsCreateViews.as_view(), name='add'),
    path('del/<int:pk>', StudentsDeleteView.as_view(), name='del'),
    path('edit/<int:pk>', StudentsUpdateViews.as_view(), name='edit'),
]

src/teacher/urls.py
from django.urls import path

from teacher.views import TeacherCreateViews, TeacherListView, \
    TeacherUpdateViews, TeacherDeleteViews

app_name = 'teacher'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('edit/<int:pk>', TeacherUpdateViews.as_view(), name='edit'),
    path('del/<int:pk>', TeacherDeleteViews.as_view(), name='del'),
    path('add', TeacherCreateViews.as_view(), name='add'),
]

src/templates/base.html
<div class="container-xl">
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{title}}</title>

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
    </head>
    <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">LMS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'students:list' %}"> Students <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'group:list' %}"> Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teacher:list' %}"> Teachers</a>
                </li>

            </ul>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}

                <div class="media">
                    <div class="img-circle.vert">
                        <img class="rounded-circle p-1 m-1" width="50" height="50" src="{{ user.profile.image.url }}">
                    </div>
                </div>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile({{ user.username }})</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'registration' %}">Register</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <h3>{{title}}</h3>
    {%block content %}
    {%endblock%}
</div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{%block content%}
<h1>Welcome to lms</h1>
{%endblock%}